(() => {
  const tg = window.Telegram && window.Telegram.WebApp;
  if (tg) { tg.ready(); tg.expand(); }
  const initData = tg ? tg.initData : "";
  const $ = id => document.getElementById(id);
  const esc = value => String(value ?? "").replace(/[&<>\"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  async function api(path, options={}) {
    const headers = {"X-Telegram-Init-Data": initData, ...(options.headers || {})};
    const response = await fetch(path, {...options, headers});
    const data = await response.json();
    if (!response.ok) throw new Error(data.error || `Request failed (${response.status})`);
    return data;
  }
  function render(data) {
    const channels = data.channels || [], tasks = data.tasks || [], broadcasts = data.broadcasts || [];
    $("summary").innerHTML = `<div class="card"><strong>${channels.length}</strong><span>Destinations</span></div><div class="card"><strong>${tasks.length}</strong><span>Recommended tasks</span></div><div class="card"><strong>${broadcasts.length}</strong><span>Recent campaigns</span></div>`;
    $("channels").innerHTML = channels.length ? channels.map(c => `<div class="item"><div><b>${esc(c.username || c.destination)}</b><div class="muted">${esc((c.categories||[]).join(", "))}</div></div><span class="pill">${esc(c.status)}</span></div>`).join("") : `<div class="muted">No destinations registered.</div>`;
    const cats = [...new Set(tasks.map(t => t.category))];
    const selected = $("category").value; $("category").innerHTML = `<option value="">All categories</option>` + cats.map(c => `<option ${c===selected?"selected":""}>${esc(c)}</option>`).join("");
    $("tasks").innerHTML = tasks.length ? tasks.map(t => `<div class="item"><div><b>${esc(t.title)}</b><div class="muted">${esc(t.category)}</div></div><span class="pill">🪙 ${esc(t.reward_amount)} Mint</span></div>`).join("") : `<div class="muted">No eligible tasks.</div>`;
    $("broadcasts").innerHTML = broadcasts.length ? broadcasts.map(b => { const d=b.deliveries||{}; return `<div class="item"><div><b>${esc(b.title || b.campaign_id)}</b><div class="muted">${esc(b.status)} · sent ${esc(d.sent||0)} · pending ${esc(d.pending||0)} · failed ${esc(d.failed||0)}</div></div><span>${["queued","running"].includes(b.status)?`<button data-action="pause" data-id="${esc(b.campaign_id)}">Pause</button>`:b.status==="paused"?`<button data-action="resume" data-id="${esc(b.campaign_id)}">Resume</button>`:b.status==="draft"?`<button data-action="queue" data-id="${esc(b.campaign_id)}">Queue</button>`:""}</span></div>`}).join("") : `<div class="muted">No campaigns.</div>`;
    document.querySelectorAll("[data-action]").forEach(button => button.onclick = async () => { try { await api(`/api/admin/broadcasts/${encodeURIComponent(button.dataset.id)}/${button.dataset.action}`, {method:"POST",headers:{"Content-Type":"application/json","X-Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({reason:"Admin Mini App action"})}); refresh(); } catch (error) { $("notice").textContent = error.message; } });
  }
  async function loadSecondary(data) {
    try {
      const audit = await api(`/api/admin/audit?object_type=${encodeURIComponent($("audit-type").value)}&limit=20`);
      $("audit").innerHTML = audit.events.length ? audit.events.map(e => `<div class="item"><span>${esc(e.object_id)} · ${esc(e.action)}</span><span class="muted">${esc(e.reason)}</span></div>`).join("") : `<div class="muted">No audit events.</div>`;
      const histories = await Promise.all((data.channels || []).map(c => api(`/api/admin/performance/${encodeURIComponent(c.destination)}?limit=3`)));
      $("performance").innerHTML = histories.length ? histories.map(h => `<div class="item"><div><b>${esc(h.destination_id)}</b><div class="muted">${h.current ? `${esc(h.current.tier)} · score ${esc(h.current.score)}` : "No observations"}</div></div><span>${h.control && Number(h.control.cooldown_until) > Math.floor(Date.now()/1000) ? `<button data-performance-clear="${esc(h.destination_id)}">Clear cooldown</button>` : `<span class="pill">${h.history.length} snapshots</span>`}</span></div>`).join("") : `<div class="muted">No performance history.</div>`;
      document.querySelectorAll("[data-performance-clear]").forEach(button => button.onclick = async () => { try { await api(`/api/admin/performance/${encodeURIComponent(button.dataset.performanceClear)}/clear`, {method:"POST",headers:{"Content-Type":"application/json","X-Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({reason:"Admin Mini App intervention"})}); refresh(); } catch (error) { $("notice").textContent = error.message; } });
      const period = $("period").value || new Date().toISOString().slice(0,7);
      try { const referral = await api(`/api/admin/referrals/${encodeURIComponent(period)}`); $("referrals").innerHTML = `<div class="item"><div><b>${esc(referral.period)}</b><div class="muted">${esc(referral.status)} · pool ${esc(referral.pool)} · winners ${esc(referral.winners)}</div></div>${referral.status === "preview" ? `<button id="approve-referral">Approve</button>` : `<span class="pill">Finalized</span>`}</div>`; const approve = $("approve-referral"); if (approve) approve.onclick = async () => { await api(`/api/admin/referrals/${encodeURIComponent(period)}/approve`, {method:"POST",headers:{"Content-Type":"application/json","X-Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({reason:"Admin Mini App approval"})}); refresh(); }; } catch (_) { $("referrals").innerHTML = `<div class="muted">No snapshot for ${esc(period)}.</div>`; }
    } catch (error) { $("notice").textContent = error.message; }
  }
  const post = (path, body) => api(path, {method:"POST",headers:{"Content-Type":"application/json","X-Idempotency-Key":crypto.randomUUID()},body:JSON.stringify(body)});
  async function loadSafety() {
    try {
      const safety = await api("/api/admin/safety");
      const st = safety.status || {};
      $("safety-status").textContent = `${st.safe_mode && st.safe_mode.enabled ? "SAFE MODE ON" : "normal"} · ${st.open_reports||0} reports · ${st.open_appeals||0} appeals`;
      const reports = safety.reports || [], appeals = safety.appeals || [];
      $("reports").innerHTML = reports.length ? reports.map(r => `<div class="item"><div><b>${esc(r.entity_type)} ${esc(r.entity_id)}</b><div class="muted">${esc(r.status)} · ${esc(r.reason)} · by ${esc(r.reporter_id)}</div></div><span><button data-report="${esc(r.report_id)}" data-status="UNDER_REVIEW">Review</button><button data-report="${esc(r.report_id)}" data-status="DISMISSED">Dismiss</button><button data-report="${esc(r.report_id)}" data-status="WARNED">Warn</button><button data-report-restrict="${esc(r.report_id)}" data-entity="${esc(r.entity_id)}" data-type="${esc(r.entity_type)}">Restrict</button></span></div>`).join("") : `<div class="muted">No open reports.</div>`;
      $("appeals").innerHTML = appeals.length ? appeals.map(a => `<div class="item"><div><b>${esc(a.entity_type)} ${esc(a.entity_id)}</b><div class="muted">${esc(a.status)} · ${esc(a.statement)}</div></div><span><button data-appeal="${esc(a.appeal_id)}" data-decision="UNDER_REVIEW">Review</button><button data-appeal="${esc(a.appeal_id)}" data-decision="UPHELD">Uphold</button><button data-appeal="${esc(a.appeal_id)}" data-decision="OVERTURNED">Overturn</button></span></div>`).join("") : `<div class="muted">No open appeals.</div>`;
      document.querySelectorAll("[data-report]").forEach(b => b.onclick = async () => { const notes = prompt(`Notes for ${b.dataset.status}:`) || ""; try { await post(`/api/admin/reports/${encodeURIComponent(b.dataset.report)}/review`, {status:b.dataset.status, notes}); loadSafety(); } catch (e) { $("safety-result").textContent = e.message; } });
      document.querySelectorAll("[data-report-restrict]").forEach(b => b.onclick = async () => { const reason = prompt("Reason for RESTRICT (required; owner only):"); if(!reason) return; try { await post(`/api/admin/enforcement/${encodeURIComponent(b.dataset.type)}/${encodeURIComponent(b.dataset.entity)}/restricted`, {reason, related_report_id:b.dataset.reportRestrict}); loadSafety(); } catch (e) { $("safety-result").textContent = e.message; } });
      document.querySelectorAll("[data-appeal]").forEach(b => b.onclick = async () => { const notes = prompt(`Notes for ${b.dataset.decision}:`) || ""; if (b.dataset.decision === "OVERTURNED" && !confirm("Overturning restores the entity to ACTIVE. Continue?")) return; try { await post(`/api/admin/appeals/${encodeURIComponent(b.dataset.appeal)}/decide`, {decision:b.dataset.decision, notes}); loadSafety(); } catch (e) { $("safety-result").textContent = e.message; } });
    } catch (error) { $("safety-status").textContent = "unavailable"; }
  }
  $("file-report").addEventListener("click", async () => { const entity_id=$("report-entity-id").value.trim(), entity_type=$("report-entity-type").value, reason=$("report-reason").value.trim(); if(!entity_id||!reason){$("safety-result").textContent="Entity ID and reason are required";return;} try { await post("/api/admin/reports", {entity_id, entity_type, reason}); $("report-reason").value=""; loadSafety(); } catch(e){$("safety-result").textContent=e.message;} });
  async function refresh() {
    $("notice").textContent = "Loading authenticated dashboard…";
    try { const query = new URLSearchParams(); if ($("category").value) query.set("task_category", $("category").value); if ($("broadcast-status").value) query.set("broadcast_status", $("broadcast-status").value); const data = await api(`/api/admin/dashboard?${query}`); render(data); await loadSecondary(data); await loadSafety(); $("notice").textContent = "Authenticated dashboard"; }
    catch (error) { $("notice").textContent = `Unable to load dashboard: ${error.message}`; }
  }
  $("create-broadcast").addEventListener("click", async () => { const title = $("broadcast-title").value.trim(), text = $("broadcast-text").value.trim(); if (!title || !text) { $("notice").textContent = "Campaign title and text are required"; return; } const scheduled = $("broadcast-scheduled").value ? Math.floor(new Date($("broadcast-scheduled").value).getTime()/1000) : null; try { await api("/api/admin/broadcasts", {method:"POST",headers:{"Content-Type":"application/json","X-Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({title,text,scheduled_at:scheduled})}); $("broadcast-text").value=""; refresh(); } catch (error) { $("notice").textContent = error.message; } });
  $("apply-safety").addEventListener("click", async () => { const entityId=$("safety-entity-id").value.trim(), reason=$("safety-reason").value.trim(), entityType=$("safety-entity-type").value, action=$("safety-action").value; if(!entityId||!reason){$("safety-result").textContent="Entity ID and reason are required";return;} if(!confirm(`Apply ${action} to ${entityType} ${entityId}?`)) return; try { const result=await api(`/api/admin/enforcement/${encodeURIComponent(entityType)}/${encodeURIComponent(entityId)}/${action}`,{method:"POST",headers:{"Content-Type":"application/json","X-Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({reason})}); $("safety-result").textContent=`${result.state} recorded for ${entityType} ${entityId}`; } catch(error){$("safety-result").textContent=error.message;} });
  $("toggle-safe-mode").addEventListener("click", async () => { const enabled=!confirm("Press Cancel to enable emergency safe mode; press OK to disable it."); const reason=prompt("Reason for changing emergency safe mode:"); if(!reason)return; try { const result=await api("/api/admin/safety/emergency",{method:"POST",headers:{"Content-Type":"application/json","X-Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({enabled,reason})}); $("safety-result").textContent=`Safe mode ${result.enabled?"enabled":"disabled"}`; }catch(error){$("safety-result").textContent=error.message;} });
  $("refresh").addEventListener("click", refresh); $("category").addEventListener("change", refresh); $("broadcast-status").addEventListener("change", refresh); $("audit-type").addEventListener("change", refresh); $("period").addEventListener("change", refresh); refresh();
})();
